version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./Alpha_src:/
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - og-network
    php:
        image: php:fpm
        volumes:
            - ./Alpha_src:/
        networks:
            - og-network

networks:
    og-network:
        driver: bridge
